### ISSUE TITLE
The typeof store is string, causing trouble when using react-use-flexsearch

### ISSUE THREAD

**Issue by adonig** [angeloashmore/gatsby-plugin-local-search#18]
I use `gatsby-plugin-local-search` together with `react-use-flexsearch`. My index and store coming from graphql are both strings. That causes `useFlexsearch(query, index, store)` not to work, because it uses an array access `store[id]`, which fails when the store is a string instead of an object.

My workaround is `useFlexSearch(query, index, JSON.parse(store))`, but I think either `gatsby-plugin-local-search` or `react-use-flexsearch` should do the conversion instead.

**Comment by angeloashmore** [comment]
Hi @adonig, I agree, `gatsby-plugin-local-search` should be returning JSON, not a string. This was the original intent, but this plugin was written while Gatsby was just introducing its schema customization API which, at the time, included a bug when declaring JSON types.

I started converting the project to TypeScript back in January which includes this fix. Once that's ready to publish, we'll need to publish as `v2.0.0` since changing the type is a breaking change.

You can see the changes here: https://github.com/angeloashmore/gatsby-plugin-local-search/blob/aa/ts/src/gatsby-node.ts

**Comment by seaneking** [comment]
Also ran into this, would be good to update the example in the README/document this limitation in the meantime.

**Comment by angeloashmore** [comment]
Thanks for the nudge, just published `v2.0.0`. Let me know if you run into any issues using the new version. 👍

**Breaking change described here**:
https://github.com/angeloashmore/gatsby-plugin-local-search/blob/master/CHANGELOG.md#200-next0-2020-07-11

Along with returning JSON, there are also new `publicIndexURL` and `publicStoreURL` fields that may be useful.

**URL fields described here**:
https://github.com/angeloashmore/gatsby-plugin-local-search#lazy-loading-the-index-andor-store
