### ISSUE TITLE
Default: all fields

### ISSUE THREAD

**Issue by corneliugaina** [angeloashmore/gatsby-plugin-local-search#53]
In the gatsby-config example, it says for index and store there's an 'default' option to expose all fields.
However it's not self-explanatory and I tried several options whitout success.

Anybody can explain how I can expose all the properties of normalizer without writing what fields should be in index and store ?

        // List of keys to index. The values of the keys are taken from the
        // normalizer function below.
        // Default: all fields
        index: ['title', 'body'],

        // List of keys to store and make available in your UI. The values of
        // the keys are taken from the normalizer function below.
        // Default: all fields
        store: ['id', 'path', 'title'],

**Comment by nashvinxtn** [comment]
Any news on this issue.

**Comment by angeloashmore** [comment]
Hey @corneliugaina and @nashvinxtn,

If you would like to index and/or store all fields, you can simply omit the option. If you don't specify a list of index or store keys, the lists will default to all keys.

Here is an example:

```ts
// gatsby-config.js

module.exports = {
  plugins: [

    {
      resolve: 'gatsby-plugin-local-search',
      options: {
        name: 'pages',
        engine: 'flexsearch',
        query: `
          {
            # Your query
          }
        `,
        normalizer: ({ data }) => {
          // Your normalizer
        }
      },
    },
  ],
}
```

Because the `index` and `store` options are not included, each of them will default to all of your keys. You can also choose to include just `index` or just `store`, or both.
